spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;
    username: sang
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 어플리케이션 생성 시점에서 기존을 지우고 다시 테이블을 생성
    properties:
        hibernate:
 #        show_sql: true
          format_sql: true

logging.level:
  org.hibernate.SQL: debug #sql 내역이 다 보임... logger를 통해서
  org.hibernate.type: trace